### ISSUE TITLE
Difficulty to make a component with complex CSS selectors

### ISSUE THREAD

**Issue by matschik** [morishitter/picostyle#51]
Hi !
Thanks a lot for this lightweight library !

I'm experiencing difficulties with this piece of CSS to a Picostyle wrap component. Anybody got a solution for this complex piece of CSS ?

```css

/* Dynamic columns */
/* one column */
.dcolumn:first-child:nth-last-child(1) {
  float: left;
  width: 100%;
}

/* two columns */
.dcolumn:first-child:nth-last-child(2),
.dcolumn:first-child:nth-last-child(2) ~ .dcolumn {
  float: left;
  width: 50%;
}

/* three columns */
.dcolumn:first-child:nth-last-child(3),
.dcolumn:first-child:nth-last-child(3) ~ .dcolumn {
  float: left;
  width: 33.3333%;
}

/* four columns */
.dcolumn:first-child:nth-last-child(4),
.dcolumn:first-child:nth-last-child(4) ~ .dcolumn {
  float: left;
  width: 25%;
}
```
